id: 03f9b65abd7e4810b16e11e6f05c4291
initial_creation_type: ebook
source_metadata:
  title: Tsadra test
  subtitle: Tsadra test
  authors:
  - Tsadra test
  collection: Tsadra test
  publisher: tsadra
  id: test
  cover: tmpezc59jg_.jpg
  credit: tmp1rqwo00n.jpg
